### PR TITLE
Sort and cleanup config

### PR DESCRIPTION
**Pull request by MichaIng**
+ Remove doubled, comment unused and describe all Markdown extensions
+ Align navigation word capitalisation and use "&" instead of "/" for multi-purpose software categories
+ Do not store HTML override file inside the docs directory, as it is conditionally merged into the actual HTML files and itself is no valid HTML file.

### CODE REVIEW

**Comment by MichaIng** [comment]
@fpetru @StephanStS 
I had a look through the Markdown extensions, what they do and which we use. I commented the ones we do not use and checked locally that all renders the same and that indeed the related HTML tags were not present in the generated HTML files before.

But actually some of them can do nice things:
- Nice symbols to show when keyboard keys need to be pressed: https://facelessuser.github.io/pymdown-extensions/extensions/keys/
- Highlight code syntax as well for inline code snippets: https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/
- Automatic shortcut URLs to GitHub, Twitter and other providers with nice symbols: https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/#mentions
- Abbreviations with long-form popups: https://python-markdown.github.io/extensions/abbreviations/
  - That is useful in combination with insert snippets: https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
    So we could create a markdown file which only holds often used abbreviations and insert it into the bottom all other Markdown files. At least I think the definitions need to be present in each Markdown document.
- Footnotes: https://python-markdown.github.io/extensions/footnotes/
- A bunch of text format things like subscript, superscript, mathematical terms in general etc are possible as well. easy symbol syntax for arrows, copyright sign an stuff like that.

So when missing something, it is always worth to have a look into the two extension sources linked above which are widely used, well documented and in case of `@facelessuser` a very responsive and friendly developer I can say.

**Comment by fpetru** [comment]
@MichaIng - Please keep snippets - started to use them in the last PR I've made - [code blocks in MkDocs Material](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#snippets)

**Comment by MichaIng** [comment]
Are you sure? At least there is no single appearance of the include syntax `'--8<--'`. Note that the code blocks documentation you linked lists a bunch of other extensions which are used within the presented examples, in this case one that shows that as well source code files can be included into fenced code syntax: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#embedding-external-files
But so far we do not use this feature and that particular example is not something that we can reasonably use.

About magiclink, yes e.g. we can use it to link `@MichaIng` to the GitHub user account automatically. Also, on first rough read-through, it should be possible to create links like `@phpbb:MichaIng` to link to https://dietpi.com/phpbb/memberlist.php?username=MichaIng. Sadly I couldn't find a phpBB link to a user profile page based on a username, but only user ID, but at leads the user list filtered by a specific name is possible.

However, I'll merge it for now and whenever someone finds time to make use of an additional extension, it makes sense to enable it just within the same pull request.

**Comment by fpetru** [comment]
@MichaIng - yes, on snippets I've referred to show the code in a better way than the default (having a copy button), and render it with specific language lexer. It looks and runs better than default markdown.

``` bash
markdown_extensions:
  - pymdownx.snippets
```

Magiclink I have not used it, and I will enable it as soon as I start including it.

**Comment by MichaIng** [comment]
> yes, on snippets I've referred to show the code in a better way than the default (having a copy button), and render it with specific language lexer. It looks and runs better than default markdown.

But that is not due to the `snippets` extension but due to the `superfences` extension, which adds the copy button and allows code syntax highlighting and all that 😉.

**Pull request merged**
