### PR TITLE
Hint added regarding updating mkdocs problems

### PR DESCRIPTION
**Pull request by StephanStS**

### CODE REVIEW

**Comment by MichaIng** [comment]
Be careful with mixing root and non-root `pip` executions, since they do entirely different things. `pip` as non-root users installs modules into the user's `~/.local` directory, which is not in the `PATH` by default, i.e. running `mkdocs` would fail as it cannot be found. `pip` also loudly warns about this:
```console
  WARNING: The script watchmedo is installed in '/home/dietpi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script markdown_py is installed in '/home/dietpi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script ghp-import is installed in '/home/dietpi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mkdocs is installed in '/home/dietpi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```
Running `pip` as root, installs modules into `/usr/local`, where binaries and libraries can be found system-wide.

It is hence important to either install `mkdocs` (or any other module) only as root user right from the start, to make it available system-wide, or as non-root user right from the start, either executing binaries with path or adding `~/.local/bin` to PATH. Another solution would be a `venv`. Describing all ways of installing Python modules goes beyond of what should go into a README, so we must rely on users knowing how they installed `mkdocs` initially and stick with that way for updates. This is also why I did not add `sudo` to the install command in the first place.

**Comment by StephanStS** [comment]
> Be careful with mixing root and non-root `pip` executions, since they do entirely different things. `pip` as non-root users installs modules into the user's `~/.local` directory, which is not in the `PATH` by default, i.e. running `mkdocs` would fail as it cannot be found. `pip` also loudly warns about this:
> 

Whatsoever: What to do if (caused by an mkdocs update) the command `sudo mkdocs serve` does not work anymore and a `pip` execution does not fix the problem?
Then, a `sudo pip ...` may help.
That was the goal to describe. Is there another solution idea to deal in this case?

**Comment by MichaIng** [comment]
The question then is why you did run `pip` as non-root user without `sudo`, while running `mkdocs` with `sudo`. What you suggest here is to install/update two independent MkDocs instances, including all dependencies, of which one remains unused. That does not make so much sense, but it's better to understand/learn how `pip` works in which cases, and fix it properly, including the decision of whether if shall/can be a root/system instance, or a user instance.

If we really want to make this fool-prove, we instead could add `sudo` to the install/serve commands in the first place, to assure it is and remains installed/updated/served as root user. But from security point of view, that is actually problematic for users who do not know what they are doing, but better to keep it a non-root instance entirely and follow the `pip` warnings regarding the `PATH`. However, this is a repo for us and for contributors of the the DietPi docs, not a general `pip` or MkDocs repo for general usage where going into detail about how to run it makes sense, IMO.

**Comment by MichaIng** [comment]
> What to do if (caused by an mkdocs update) the command `sudo mkdocs serve` does not work anymore and a `pip` execution does not fix the problem?

Ah sorry for not actually answering the question 😅. "does not work anymore" is very unspecific, so generally more info would be required to know the right solution. However, in your particular case:
1. If you want `mkdocs` installed system-wide, `sudo pip3 install` is right, but one should cleanup the user's instance as well:
    ```sh
    pip3 uninstall -y $(pip3 freeze --user | mawk -F= '{print $1}')
    ```
    This removes all Python modules of the user, assuming non-root execution of `pip` was an accident.
2. If you want `mkdocs` installed for the current user, then you may remove the one installed system-wide instead, or all system-wide installed modules (aside of `pip`, `setuptools` and `wheel`):
    ```sh
    sudo pip3 uninstall -y $(sudo pip3 freeze | mawk -F= '{print $1}')
    ```
    `mkdocs` then needs to be executed like this:
    ```sh
    ~/.local/bin/mkdocs serve
    ```
    Or added to PATH:
    ```sh
    export PATH="$HOME/.local/bin:$PATH"
    mkdocs serve
    ```
    Permanently:
    ```sh
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
    ```

**Comment by StephanStS** [comment]
Thx for the explanation. So, an uninstall/install with the commands above could also be an option in case of problems?
That would be a much more foolproof procedure. :-)

**Comment by MichaIng** [comment]
> So, an uninstall/install with the commands above could also be an option in case of problems?

It is a very specific issue you ran into, so I wouldn't suggest to run those generally in case of issues with MkDocs.

> That would be a much more foolproof (= StephanStS-proof) procedure. :-)

😄, I hope it is now clear that you updated/installed MkDocs on a user level, but executed the (too old) version (actually too old `mkdocs-material` as of recent update, if I'm not mistaken) from system level. On a non-production testing system, consequently using `sudo` for `pip` should be easiest to have everything available system-wide and in PATH directly. If `pip` was run without `sudo` as non-root user accidentally, I usually "uninstall" (purge) everything the quick way like that, which includes the `pip` cache and the `nano` search history 🙄, but on an otherwise clean DietPi nothing else:
```sh
rm -R ~/.local ~/.cache
```

**Comment by StephanStS** [comment]
Ok, I removed the both options, cleared .local and .cache and restarted the installation without sudo. 
Now, all is fine, `mkdocs serve` works.. :-)

**Comment by StephanStS** [comment]
So I think, the sudo stuff was based on problems longer ago. I always used `sudo mkdocs serve` in the past.
So with the description completely without sudo, we should better close (not merge) this PR.

**Pull request closed without merging**
