### PR TITLE
Add information for the ADSB Feeder software

### PR DESCRIPTION
**Pull request by dirkhh**
this corresponds to https://github.com/MichaIng/DietPi/pull/6587

Again, I'd love to hear feedback on format, content, anything.

### CODE REVIEW

**Comment by StephanStS** [comment]
@dirkhh: I do not find the .png files referenced in the doc.

**Comment by dirkhh** [comment]
🤦🏻‍♂️
will fix in a moment.

**Comment by dirkhh** [comment]
fixed a typo and added a note about the default port. I think this is ready for use once the [underlying PR](https://github.com/MichaIng/DietPi/pull/6587) for the `dietpi-software` app has been merged.

**Comment by StephanStS** [comment]
I'd like to process PR https://github.com/dirkhh/DietPi-Docs/pull/1 and afterwards go ahead in this repo.

**Comment by dirkhh** [comment]
Thank you so much! I appreciate the edits to my proposed changes so they fit better into the existing style.

**Comment by StephanStS** [comment]
@MichaIng : Could you please merge this PR although it has errors. It is easier for me to fix typo via wordlist in the dev branch of this repo.

**Comment by MichaIng** [comment]
Let's wait with merging until beta week, otherwise we cannot merge `dev` to `master` anymore, which I might want to do as of changed image archive compression.

**Comment by MichaIng** [comment]
Is it not possible for you to push to this branch, e.g. when selecting the PR in GitHub desktop? All maintainers of the base branch should have write access.

**Comment by dirkhh** [comment]
> Is it not possible for you to push to this branch, e.g. when selecting the PR in GitHub desktop? All maintainers of the base branch should have write access.

It should be - when I submitted the PR it explicitly told me that maintainers can modify my branch. And you are of course welcome to do so, @StephanStS

**Comment by StephanStS** [comment]
> > Is it not possible for you to push to this branch, e.g. when selecting the PR in GitHub desktop? All maintainers of the base branch should have write access.
> 
> It should be - when I submitted the PR it explicitly told me that maintainers can modify my branch. And you are of course welcome to do so, @StephanStS

Thx for the input, with Micha's help I am now able to push directly into your PR here.

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
