### PR TITLE
DietPi-Software | vaultwarden: Rename from Bitwarden_RS

### PR DESCRIPTION
**Pull request by Joulinar**
DietPi-Software | vaultwarden project has been renamed

https://github.com/MichaIng/DietPi/pull/4334

### CODE REVIEW

**Comment by Joulinar** [comment]
@MichaIng 
@StephanStS 
are we able to rename the picture or do we need to upload a new one?

**Comment by MichaIng** [comment]
Files can be renamed, images not via GitHub website but via Git CLI.

**Review by StephanStS — APPROVED** [review]

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
@Joulinar 
LGTM. Please squash and merge, when ready from your side.

**Comment by MichaIng** [comment]
Shall we make it a draft until the release week has come, like we did with the changes for the last release?

**Comment by Joulinar** [comment]
Marked as draft

**Pull request merged**
