### PR TITLE
Release notes v8.15 (#855)

### PR DESCRIPTION
**Pull request by MichaIng**

### CODE REVIEW

**Review by StephanStS — APPROVED** [review]

**Comment by MichaIng** [comment]
An immediate retry after lychee link check timeout errors usually does not help but makes it worse, since such usually caused by rate limiting. Just ignore if those open fine in browser and don't show up on every check.

**Comment by MichaIng** [comment]
@StephanStS 
For the future: Let me merge these final DietPi release related PRs into `master`. This should not be done until the DietPi release has been actually done, so in the order:
1. DietPi release
2. DietPi-Docs release
3. DietPi-Website release

Until the actual release, I'm doing quite some testing and may add bug fixes to the release notes.

**Comment by StephanStS** [comment]
> An immediate retry after lychee link check timeout, network errors or similar usually does not help but makes it worse, since such usually caused by rate limiting. Just ignore if those open fine in browser and don't show up on every check.

In these cases I cannot finish the PR.

**Comment by MichaIng** [comment]
That is right, but in this case not a problem or even good, as of my last post 😉.

**Pull request merged**
