### PR TITLE
Release week 01/2023

### PR DESCRIPTION
**Pull request by StephanStS**

### CODE REVIEW

**Comment by StephanStS** [comment]
@MichaIng: Please approve docu to be able to merge it.
Additionally I propose to add JappeHallunken as a further reviewer.

**Comment by MichaIng** [comment]
This shouldn't be merged before v8.13 has been released, otherwise we have false info for current stable DietPi users 😉.

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
On the other hand, the only v8.13-only info is about `SOFTWARE_URBACKUP_BACKUPPATH`, while everything else are enhancements or even other fixed info. So I'm okay with merging, once CI went through. GitHub runners have problems at the moment: https://twitter.com/githubstatus

**Comment by MichaIng** [comment]
> Additionally I propose to add JappeHallunken as a further reviewer.

For this we need to add him as collaborator to the repo. Did he agree to be pinged here for docs reviews?

**Comment by Joulinar** [comment]
I have one addition for our docs. We need to add a tap on Node.js on how to update. This is missing.

**Comment by MichaIng** [comment]
Ah right, via reinstall. A quick copy&paste will do. Are you already doing it or shall I do (all relevant files open already)?

**Comment by Joulinar** [comment]
I can do, just would need additional 2-3 hours to find time.

**Comment by MichaIng** [comment]
Done.

**Review by MichaIng — APPROVED** [review]

**Comment by StephanStS** [comment]
> > Additionally I propose to add JappeHallunken as a further reviewer.
> 
> For this we need to add him as collaborator to the repo. Did he agree to be pinged here for docs reviews?

Yes, I contacted him.

**Pull request merged**
