### PR TITLE
Preliminary start with v8.2 release notes

### PR DESCRIPTION
**Pull request by StephanStS**
Start with a first structure.

### CODE REVIEW

**Comment by MichaIng** [comment]
The spring release, hopefully we'll have some crocuses peep out of the ground that time 🙂.

**Comment by Joulinar** [comment]
> hopefully we'll have some crocuses peep out of the ground

I already have 😜

**Comment by MichaIng** [comment]
😱 unfair! Even the nearby nature reserve meadow, which is full of flowers from spring to autumn doesn't have them yet, at least I didn't recognise. Looks like the regularly crossing horses need to try harder fertilising that ground 💩.

**Comment by StephanStS** [comment]
Do not forget to update the link to the PR at the end of the 8_2 releasenotes.

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
