### PR TITLE
Corrections due to Mardown check warnings

### PR DESCRIPTION
**Pull request by StephanStS**

### CODE REVIEW

**Comment by MichaIng** [comment]
@StephanStS btw I if we want to show the raw URL as link, it is possible to wrap it into angle brackets, like:
```
<https://dietpi.com/>
```
<https://dietpi.com/>

That satisfies markdown-lint as well. But as well fine to place it onto meaningful text 👍.

**Comment by StephanStS** [comment]
@MichaIng: Is it possible to exclude the file release-notes.md from the markdownlint?

**Comment by MichaIng** [comment]
Yes I was thinking the same, probably makes sense. I'll have a look into it.

**Comment by StephanStS** [comment]
Possibly you could also remove the '?' check at the end of a header.
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md026---trailing-punctuation-in-header

**Comment by MichaIng** [comment]
This allows question marks: https://github.com/MichaIng/DietPi-Docs/pull/78
I'm sure there is a document style guide that tells that one should not ask questions in headers, but especially the first question is, based on our current degree of being known, pretty perfect there, IMO.

**Pull request merged**
