### PR TITLE
Release week 51

### PR DESCRIPTION
**Pull request by StephanStS**
I propose to release the current status.

### CODE REVIEW

**Comment by MichaIng** [comment]
I need to update the OctoPrint docs as of the changes with v6.34. Will do that tomorrow.

**Comment by fpetru** [comment]
I am also bringing some changes to release notes - mainly to bring links to the 6.34 items

**Comment by fpetru** [comment]
@StephanStS - fully updated the web development section

**Comment by MichaIng** [comment]
I refreshed the test build: https://dietpi.com/test/
Looks pretty fine to me 👍.

**Review by MichaIng — DISMISSED** [review]

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
