### PR TITLE
Release week 6

### PR DESCRIPTION
**Pull request by StephanStS**

### CODE REVIEW

**Review by fpetru — APPROVED** [review]

**Comment by MichaIng** [comment]
Docker legal team did not yet answer our question whether we're allowed to use their logo. What shall we do about it, proceed or comment out the images for now?

**Comment by Joulinar** [comment]
Well we could leave it out for the moment. That would be safest

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
Done

**Comment by MichaIng** [comment]
Ignore the missing layer 1 header in README.md. It's allowed since just a few days and the markdownlint-cli2 that we use still needs to be updated: https://github.com/DavidAnson/markdownlint/issues/366

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
