### PR TITLE
Migrate to lychee for link checking

### PR DESCRIPTION
**Pull request by MichaIng**
as liche has been deprecated by its developer. But there are a few issues that need to be addressed first:
- [x] Relative or absolute file links can only be checked against an online URL, which is bad when we change internal file structure/names and quite some overhead, compared to checking the existence of local files. liche has currently a reasonable implementation for these cases: https://github.com/lycheeverse/lychee/issues/21
    **EDIT: Solved by running `mkdocs serve` as a local webserver and check internal lings against it.**
- [x] By default GET requests are used, which in theory would mean whole file downloads (e.g. all our image archive links), being a problem for our OS image links. It can be changed to HEAD via "-X head" option, so this is no blocking topic, but a very nice automatic fallback from default HEAD to GET might be implemented: https://github.com/lycheeverse/lychee/issues/27
- [x] HTML parsing issues: https://github.com/lycheeverse/lychee/issues/83
**EDIT: All full URLs do work now with a new implemented HTML parser 👍.**

### CODE REVIEW

**Comment by ravenclaw900** [comment]
Thoughts on using [`continue-on-error: true`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) instead of `if: always() && steps.etc.outcome == 'success'`?

**Comment by MichaIng** [comment]
Good to know about that option. However, often one step is required for the following step but not for the step afterwards, e.g. checking spelling can only work if pyspelling got successfully build, but link checking can still be done. I think this can currently only be correctly handled the way it is done now.

**Comment by ravenclaw900** [comment]
Also, (more related to this PR), why not use the actual lychee action? https://github.com/lycheeverse/lychee-action

**Comment by MichaIng** [comment]
The question is why should we? 🙂
It adds more complexity outside of our control and implies some overhead to download and start the Docker container. I generally like to use the actual tools directly to have full control over the environment, version and command options.

Those GitHub action containers are generally nice to get started fast and easy without doing things like manual builds (or download and extract in case of lychee), but finally it does nothing more than executing the same tool, so from that state on has no benefit.

**Comment by MichaIng** [comment]
Since currently local file checks seems to be no prioritised feature in lychee, an alternative is to use `mkdocs serve` to run a local webserver. Then for local links, we can set a base URL to `http://127.0.0.1/`. I'm a bit annoyed by the constantly failing tests because of liche timeouts and hope this gets better with lychee.

**Comment by MichaIng** [comment]
It required some more changes and more complex integration, but now it works fine. It's worth it to reduce checks process time and timeout errors that liche suffered from. Positive side-effects are:
- that "mkdocs serve" does not do automatic redirects from URLs without trailing `/` to with trailing `/`, so it that all URLs are given a way that no redirect is required (slightly reduced overhead, for checks and also for search engine crawlers etc)
- that now outdated URLs which only worked because of our [migration redirects](https://github.com/MichaIng/DietPi-Docs/blob/80cee8d/mkdocs.yml#L75-L83) are failing the test, so we see and can update them

Negative is that URLs in code blocks are checked as well, which required some additional exclusions when we used things like `http://192.168.0.100:8123`. But it forces us to consequently use `http://<your.IP>:8123` as a standard, which is good. There are a few cases left where we use localhost or loopback IP correctly to explain how to access InfluxDB via CLI or a Syncthing instance running on a Windows machine from the browser. Excludes based on tags is a feature that would be great for lychee. liche didn't have that issue since it only checked URLs in `<a` tags and `href=` attributes of `<link` tags, or so, not every URL found anywhere in the document.

Since we need to check every directory with a separate call, we have many summary prints in the checks output. Not awesome, but acceptable.
One failing check yesterday is solved now: https://detechter.com/the-battle-of-the-web-servers-apache-vs-Nginx-vs-lighttpd-2/
The last one is for https://www.audiophonics.fr, where OpenSSL reports "Verification error: unable to verify the first certificate", while my browsers don't see any issue and the certificate + chain looks all correct. I'll exclude it for now so that we get green checks, finally 😄.

**Comment by MichaIng** [comment]
It's not as fast as on the main website, I guess mostly since we need to do a single call for each HTML to have internal links checked correctly. This also means that same URLs are checked doubled. And it's about 3000 overall links, so MUCH more 😄.

Ready from my end.

**Pull request merged**
