### PR TITLE
Release notes 6.34

### PR DESCRIPTION
**Pull request by fpetru**
Extended release notes

### CODE REVIEW

**Comment by fpetru** [comment]
@MichaIng - please help me with a screenshot showing banner when updates are discovered (with `CONFIG_CHECK_APT_UPDATES = 1`)

**Comment by MichaIng** [comment]
Is that one okay? https://twitter.com/DietPi_/status/1336729761335406592/photo/1
We can replace it with a master branch one once released 😉.

Btw, probably we can add phpBB forum member links via magic links extension, with a custom syntax or such. Otherwise we need to take care that those are not falsely converted into GitHub profile links. Here is the best what we can do with phpBB: https://dietpi.com/phpbb/memberlist.php?username=MichaIng
Not sure if it's worth it 🤔.

**Comment by fpetru** [comment]
@MichaIng 

> Is that one okay? https://twitter.com/DietPi_/status/1336729761335406592/photo/1
> We can replace it with a master branch one once released 😉.

Yes, agree.

> ~Btw, probably we can add phpBB forum member links via magic links extension, with a custom syntax or such.~ (**EDIT: Curently magicmirror does not allow custom providers, so those link would need to be added manually.**) Otherwise we need to take care that those are not falsely converted into GitHub profile links. Here is the best what we can do with phpBB: https://dietpi.com/phpbb/memberlist.php?username=MichaIng
> Not sure if it's worth it 🤔.

Right. Let me check.

**Comment by fpetru** [comment]
Extended release notes with DietPi 6.34 updates. Bring more details to new software titles.

**Pull request merged**
