### PR TITLE
Update all image downloads to Bookworm

### PR DESCRIPTION
**Pull request by MichaIng**
aside of NanoPi M2/M3/Fire3 and Sparky SBC where we cannot provide Bookworm since their ancient kernel lacks needed features.

### CODE REVIEW

**Comment by Joulinar** [comment]
Do we really go to Bookworm already? Because last time from Buster it was way to fast and we had several issues with a couple of apps.

**Comment by MichaIng** [comment]
> Because last time from Buster it was way to fast and we had several issues with a couple of apps.

This is why I was writing and promoting the upgrade script and focused on all the install tests the last weeks. But I will finish the tests first and check how much fixes I needed to make. Probably pushing either live patches or an intermediate DietPi v8.18.3, before merging this PR. Ah and this dbus/logind error message on shutdown/reboot.

**Comment by Joulinar** [comment]
> Ah and this dbus/logind error message on shutdown/reboot.

Yep that would be something to fix or work around. Otherwise we will have quite some reports 🤣

**Comment by MichaIng** [comment]
ARMv6 RPi images need to stay at Bullseye until PHP 8.2 runs on this arch: https://bugs.launchpad.net/raspbian/+bug/1998136

**Pull request merged**
