### PR TITLE
Release week 50

### PR DESCRIPTION
**Pull request by StephanStS**
Release date: 10.12.2020 (at least after PR #273 has been merged to the dev branch).

### CODE REVIEW

**Comment by StephanStS** [comment]
After this release, update/extend <https://github.com/MichaIng/DietPi/pull/3962>.

**Comment by StephanStS** [comment]
@MichaIng: I propose to finish the PR. Several smaller additions have been added. I do not expect further contents for now.

**Comment by MichaIng** [comment]
I'll add a little fix I recognised while testing/checking IceCast.

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
Ready from my side, @StephanStS please merge when you agree.

**Pull request merged**
