### PR TITLE
Release notes (January 2022)

### PR DESCRIPTION
**Pull request by fpetru**
Bring _Release Notes_ to a distinct item, in the main menu. The notes document became too long, almost impossible to read

### CODE REVIEW

**Comment by fpetru** [comment]
@MichaIng @StephanStS The PR is still a draft. Let me know if you agree with this menu restructure
We keep the link `dietpi.com/docs/releases` still actual with a redirect.

**Comment by MichaIng** [comment]
Many thanks. A necessary step I'd say to keep the size of the HTML limited. And throwing away old release notes is somehow sad, so good to keep them that way.

What do you think about keeping the `releases.md` but degrading it to a link list with version string and release date, pointing to the new `vX_Y.md`'s? That way existing links on Twitter etc remain intact without any rewrite/redirect required, and also `earlier.md` could stay there in place.

**Comment by fpetru** [comment]
Yes. It's a good idea 👍. Let me make a new version with both `releases.md` and all the distinct files.

**Comment by StephanStS** [comment]
@fpetru: I also appreciate this.
My feedback is to keep the name of the tab at "Releases" instead of "Updates": Releases is more clearly defining DietPi releases. Updates may also be updates of the documentation.

And I propose to have a (release unique) graphics on the top of the relnotes. This gives a nicer view and the recognition factor of this special release is better (-> better UX). 
Examples:
- https://pixabay.com/de/photos/winter-januar-schnee-nadeln-fichte-3087709/
- https://pixabay.com/de/vectors/weise-m%c3%a4nner-flaches-design-kings-3039248/
- https://pixabay.com/de/photos/frost-winter-januar-gefroren-figur-3944523/
- https://pixabay.com/photos/icicles-frozen-cold-snow-winter-208484/
- https://pixabay.com/photos/wine-glasses-toast-holiday-6688901/
- https://pixabay.com/photos/fireworks-pyrotechnics-new-year-180553/
- </2021> --> <2022>

**Comment by fpetru** [comment]
@MichaIng @StephanStS - included changes. still work in progress

**Comment by MichaIng** [comment]
Further suggestion:
- Create new files in `docs/releases/v6_28.md`, so that the existing `releases.md` serves as parent directory index and we do not have `/release` and `/releases` one with and one without index.
- Merge `earlier.md` back into `releases.md`. The `Earlier` menu entry can be kept, but pointing to `https://dietpi.com/phpbb/viewforum.php?f=10` directly instead of a dedicated page with that link only. We could further add `releases.md` as `Overview` page, like we have it for software titles. Would be also nice as a first/default page when accessing the `RELEASES` tab:
    ```yml
    - RELEASES:
      - "Overview" : releases.md
    ```
    Not a problem that it doubles with the `HOME` navigation, IMHO. We could do the same with the software overview page to get some consistency, so not `Advanced Networking` shows up first, but the overview page/list.

**Comment by fpetru** [comment]
@MichaIng - I like the idea and this was the first idea I've tried yesterday. Still, MkDocs does not know to redirect (from `/docs/releases/#tag` to `/docs/releases/overview/#tag`. A rule embedded in the webserver will help though. Give it a try locally and let me know if you could see a solution.

>   ```yaml
>   - RELEASES:
>     - "Overview" : releases.md
>   ```

**Comment by MichaIng** [comment]
Redirects with URL fragments/parameters are not possible, so we need to accept that the old links then point to the overview page. Shouldn't be so bad when the links to the dedicated release pages are given there.

**Comment by fpetru** [comment]
@MichaIng - Has been applied any exception on the `release.md` in the past ? There are many lines which require now attention. I am curious to know why.

**Comment by MichaIng** [comment]
Indeed we excluded it from spellchecking due to the many words, usernames etc: https://github.com/MichaIng/DietPi-Docs/blob/master/.spellcheck.yml#L22

But I think it is a reasonable step to do the change and effort now. Good to have spelling checked for those pages which we advertise/link so often. The usernames are or should be excluded already together with the magiclink class: https://github.com/MichaIng/DietPi-Docs/blob/master/.spellcheck.yml#L19
But I think this does not work for the phpBB links. So those either need to be wrapped into code tags or the `nospellcheck` class added: `[phpBB:<name>](<URL>){: class="nospellcheck"}` should do it.

**Comment by fpetru** [comment]
I'm OK with the plan. Due to the long list of fixes that need to be applied, I would need some help. Alternatively, I would recommend we do it in waves (temporary excluding part of the release notes files). In my view, it will be great to start focusing on the last 5 releases (and temporary ignore the other files).

**Comment by MichaIng** [comment]
Adding `{: class="nospellcheck"}` to elements with names works. The other solution is to put them into backticks for code tags, but then there is this grey background and monotype font.

**Comment by fpetru** [comment]
Yes, added few exceptions. There are still a couple of fixes.

**Comment by fpetru** [comment]
@MichaIng - thank you. indeed it's working fine. just one change - let's keep on the left side menu, periods (month - year), instead just the versions

**Comment by MichaIng** [comment]
Please do not push any change currently as I have all spellings fixed here + more changes 😄.

**Comment by MichaIng** [comment]
I changed the navigation intentionally from month/year to DietPi versions:
- The first thing which users see on their system, scripts, updater etc is the version string. So this is the one that is easiest to remember and use as primary navigation key. If a user looks for a certain change and finds a month/year list only, (s)he will likely need to loop through a bunch of them to find the intended page.
- The other issue is that there can be multiple releases in one month, something you faced already and hence merged the related two versions in two cases into one file, which of course then is confusing as well and broke the overview links. We'd need to start with `January 2022 1` and `January 2022 2` or so, bad that looks bad.

Let's be consistent and use the version string as the primary indicator for changelogs/notes etc and have the release date/month as a secondary info, which is then sufficient to have on the actual release notes page.

**Comment by MichaIng** [comment]
Shall we make `releases.md` a bit smaller? E.g. making it a list without headers, just version - month - year as a link for each version? It looks somehow strange with these large headers and then not more than a link below each.

**Comment by MichaIng** [comment]
@fpetru 
Another thing, would you mind to use the main repository for future commits? It makes it easier to contribute for us, as all have push permissions, and I don't need to switch the local repository owner back and forth. Also then all checks run directory here and results are shown here on the PR as well + we can deploy it to the test URL.

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
Just checked, space would be sufficient to add month and year additionally to the version string to the navigation. Both is fine by me.

**Comment by fpetru** [comment]
Sure. I'll do this. In the past I was worried to mess with `master` or `dev` branches by accident.

**Comment by fpetru** [comment]
Totally fine with a more compact `releases.md`. Please adjust as suggested.

**Pull request merged**
