### PR TITLE
Add frp docs

### PR DESCRIPTION
**Pull request by ravenclaw900**

### CODE REVIEW

**Comment by Joulinar** [comment]
should we at least give 1 or 2 example on how to create a config, maybe for some specific software title?

**Comment by MichaIng** [comment]
I successfully tested AdGuard Home and HTPC-Manager behind it, so I can add one as example (tomorrow).

**Comment by fpetru** [comment]
Hi @ravenclaw900 @MichaIng @Joulinar - `frp` is a great tool and if you agree let's commit this PR, and make a new one in the future with more examples. It would be great to link this software title to the release notes.

Thank you

**Review by fpetru — APPROVED** [review]

**Comment by Joulinar** [comment]
For me that would be fine

**Comment by MichaIng** [comment]
Yes, let's do it like that, I'm a little tired today to write this. Postponed for next week 🙂.

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
