### PR TITLE
software/social: added soju IRC bouncer

### PR DESCRIPTION
**Pull request by subnut**
https://github.com/MichaIng/DietPi/pull/7124

### CODE REVIEW

**Comment by subnut** [comment]
I have no previous experience writing docs in this format, so any feedback is appreciated.

**Comment by StephanStS** [comment]
@MichaIng: Could you please merge it to an own branch (e.g. dev-StS_soju), then I can go on with editing.

**Comment by MichaIng** [comment]
@StephanStS 
It allows maintainer edits, i.e. you should be able to work on this PR as well.

**Comment by StephanStS** [comment]
> @StephanStS It allows maintainer edits, i.e. you should be able to work on this PR as well.

Sh... Always forget this.

**Review by StephanStS — APPROVED** [review]

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
