### PR TITLE
Certbot description added and  gitea description improvement

### PR DESCRIPTION
**Pull request by StephanStS**

### CODE REVIEW

**Comment by StephanStS** [comment]
@MichaIng, @fpetru: I ported the Certbot/Let's Encrypt description and moved it from ***Web Development*** to ***System Security***.

Additionally the gitea hardening with Fail2Ban and the referencing of Certbot was added.

**Comment by MichaIng** [comment]
We should leave a reference/link from webserver/stack section to Let's Encrypt section.

**Comment by StephanStS** [comment]
> 
> 
> We should leave a reference/link from webserver/stack section to Let's Encrypt section.

Yep, agree.

> 
> The Gitea Fail2Ban instructions are awesome, it could even serve as an example for a general Fail2Ban docs extension, as it's not more than that. Only how to deal with services that log to systemd-journald needs to additional example.

I am actually working on a similar issue to describe the Fail2Ban stuff with NextCloud.   
The Fail2Ban configuration is somehow target application specific, i.e. some of the configuration options are special to gitea or NextCloud. These should be described at there. They could be linked as examples for Fail2Ban.  
General Fail2Ban issues should be desribed at Fail2Ban.  

I will try to keep an eye on this.

**Comment by MichaIng** [comment]
@StephanStS 
Just found an old post on Nextcloud forum with fail2ban implementation: https://help.nextcloud.com/t/repeated-login-attempts-from-china/6510/11?u=michaing
However for the Nextcloud login mask it shouldn't be relevant anymore as it has an internal brute-force detection/prevention that can be further configured by apps: https://apps.nextcloud.com/apps/bruteforcesettings
Okay, if this is whitelisting only, then fail2ban would have the benefit to customise attempts, ban time, watch time etc.

**Comment by StephanStS** [comment]
@MichaIng: I just installed a fail2ban configuration on a Nextcloud test setup by this doc: https://www.c-rieger.de/nextcloud-installationsanleitung/#c06 (which is related to NC version 20, your link above is from 2016 and NC version 11).

I am testing this and will compare it to your link. Then I will add this hardening to the Nextcloud description.

Interesting at your link is the "general hardening" proposal to switch the standard https port from 443 to a different value.

**Comment by MichaIng** [comment]
> Interesting at your link is the "general hardening" proposal to switch the standard https port from 443 to a different value.

It was about the SSH port 😉. But could be done for HTTPS as well of course, if that does not break convenience too much for the personal use case, including Let's Encrypt cert renewal, client connections, internal and remove security scans and all this 🤔.

**Pull request merged**
