### PR TITLE
add default login and password to installation-guide page

### PR DESCRIPTION
**Pull request by dedifferentiator**
Looks like there's no default credentials on [installation guide page](https://dietpi.com/docs/user-guide_install/), though DietPi requires them at first login. These ones I found at https://dietpi.com/phpbb/viewtopic.php?t=9 , and they matched with required, maybe it would be useful to have this at main installation page too.

### CODE REVIEW

**Comment by fpetru** [comment]
Committed the change. Yes, very good point !

**Comment by MichaIng** [comment]
Many thanks! Let's keep in mind, when adding info about `dietpi.txt`-based pre-configuration, to add a small hint that on first login the password matches whatever was chosen via `AUTO_SETUP_GLOBAL_PASSWORD`, which is `dietpi` by default.

Probably a separate page about the root + dietpi UNIX user and global software password would be good (how to pre-set via dietpi.txt, how to change after first boot, the fact that it is encrypted on first run setup etc.) which we can link to from install docs and as well from individual software docs where this password is applied. So on the originating pages we don't need to go into detail, just say `"dietpi" or what you have chosen => link` or similar.

**Comment by dedifferentiator** [comment]
Oops, thereafter I rebooted DietPi and noticed that default login is displayed after booting just a couple of lines higher than the line which asks to enter it, looks like my eyes droped down on the last line and that hint left unnoticed, didn't expected it to be there, my bad :(

**Comment by MichaIng** [comment]
@dedifferentiator 
We would like to change the license for the docs from GPLv3 to CC BY-SA 4.0 (creative commons + attribution + share-alike): https://creativecommons.org/licenses/by-sa/4.0/

Since you contributed to this project, I must ask you if you allow this change 🙂.

Both are basically the same kind of open-source copyleft licenses, means you need to keep a similar/compatible license when redistributing and you need to keep attribution to previous contributions. But GPL, from details and wording, applies better so software, while CC better suites to texts, docs, websites etc.

GPLv3 is listed as compatible license for CC BY-SA 4.0, means one is allowed to redistribute CC BY-SA 4.0 licensed work under GPLv3, respectively mix CC BY-SA 4.0 licensed work into GPLv3 licensed projects: https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses
The other way round it is not possible due to some additional parts of the GPLv3 license, like the "notices about lack of warranty" and the part about patents, which both makes sense for software but not so much for documentations, websites etc. While this is the reason, I formally need to ask you, it is similarly the reason why we want to do it, so that the documentation content can be more easily integrated into other open-source projects.

**Comment by dedifferentiator** [comment]
@MichaIng  Confirmed :)

**Pull request merged**
