### PR TITLE
Harmonise indentation

### PR DESCRIPTION
**Pull request by MichaIng**

### CODE REVIEW

**Comment by MichaIng** [comment]
@fpetru @StephanStS 
Finally we are green again 🚀 🥳. Let's keep it that way from now on and wait for + assure all stays green before merging anything into `dev` branch. I could apply a strict rule so that all tests musts succeed before merging is possible, but when checking up to 256 concurrent connections against our server, either Cloudflare might trigger some DDoS protection or our server might reach it's allowed limit of currently 386 concurrent connections which leads to a 521 HTTP error response, hence a failing check. I'll check if those Cloudflare-special responses can be ignored, otherwise we need to allow them to fail to not block pull request merge for no reason.

**Comment by StephanStS** [comment]
I also think that the link check is not stable working to have a strict rule. Let's at least define that Markdown and spell check needs to run.  
@MichaIng: With the indentation you need to check the result also in the localhost:8000 output (at my setup the atom editor markdown preview and the browser display was sometimes a bit different).

**Comment by MichaIng** [comment]
> With the indentation you need to check the result also in the localhost:8000 output (at my setup the atom editor markdown preview and the browser display was sometimes a bit different).

Okay let me test. Actually the way I did this works fine on all Markdown editors/forums I know, so I'd wonder if MkDocs translated this wrong.

**Comment by MichaIng** [comment]
You are right, two white spaces do not work. Searched a bid around:
- https://stackoverflow.com/questions/62248076/syntax-highlighted-code-block-in-markdown-indented-list-paragraph
  I don't understand the solution since it is not indented then.
- Reported on MkDocs: https://github.com/mkdocs/mkdocs/issues/282
- Report on underlying Python Markdown library: https://github.com/Python-Markdown/markdown/issues/53
  Was on v3.0 milestone 5 years ago, as of dev "on top of the list" but got removed and no progress since 2015 then 😞. Issue closed so we cannot revive it, whatever the issue is that this got never fixed.

**Pull request merged**
