### PR TITLE
Pi-hole default log TTL reduced to 2 days

### PR DESCRIPTION
**Pull request by MichaIng**
I added a general section about Pi-hole implementation differences. It's good to mention the other points as well, especially that plain text file query logging (yes that is enabled by default as well, so two logs run in parallel) file is disabled. Most user will never recognise, but `pihole -t`/`pihole tail` uses this log file to print colourised logs and can hence not be used anymore.

### CODE REVIEW

**Comment by StephanStS** [comment]
I propose to move the section about the webserver in the *DietPi differences* tab: 
grafik

to an own admonition "webserver installation" to emphasize this circumstance.

I propose to use ***attention***
grafik
Alternatively we could use *important*:
grafik

The admonition could be placed direct above (or below) the screenshot.

**Comment by StephanStS** [comment]
The textual part is described very nice and clear.

**Comment by MichaIng** [comment]
@StephanStS 
Good point. You mean to move it outside of the tab or leave it inside the tab as warning? "Warning" sounds more fitting than "Tip" I think 🙂.

**Comment by MichaIng** [comment]
Done. I'll merge this and open a new release PR to test all recent changes.

**Pull request merged**
