### PR TITLE
DietPi-Software | Portainer

### PR DESCRIPTION
**Pull request by Joulinar**
Add some information how to update Portainer to latest version if needed

### CODE REVIEW

**Comment by MichaIng** [comment]
Can't this be done via docker run somehow?

**Comment by Joulinar** [comment]
Usually you need to drop the container and recreate it. However the data directly needs to stay and should not be deleted. But this is how it is scripted ATM already

**Comment by MichaIng** [comment]
A prove that I never really use Docker 😄. All fine, I just through that it supports seamless container updates without the need to manually remove them first, which would be less overhead compared to a `dietpi-software` reinstall.

**Comment by Joulinar** [comment]
ok verified it and it's working as intended. Old container is dropped and a new one is created. Thinks like user login are keeped because we keep data directory 😃 

```
 DietPi-Software
─────────────────────────────────────────────────────
 Mode: Configuring Portainer: Simplifies container management in Docker (standalone host)

[ INFO ] DietPi-Software | Docker will be restarted to be able to deploy the container.
[  OK  ] DietPi-Software | systemctl daemon-reload
[  OK  ] DietPi-Software | systemctl restart docker
[ INFO ] DietPi-Software | Portainer detected, container will be dropped before reinstallation.
[  OK  ] DietPi-Software | docker rm 67ce65a38349 --force
[  OK  ] DietPi-Software | docker rmi 1fdf590d1a36
[ INFO ] DietPi-Software | Portainer will be deployed now. This could take a while...
[ INFO ] DietPi-Software | docker run -d -p 9002:9000 --name=portainer --restart=always -v /run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce, please wait...
Unable to find image 'portainer/portainer-ce:latest' locally
latest: Pulling from portainer/portainer-ce
b890dbc4eb27: Pulling fs layer
f90a4cb1da73: Pulling fs layer
b890dbc4eb27: Verifying Checksum
b890dbc4eb27: Download complete
b890dbc4eb27: Pull complete
f90a4cb1da73: Verifying Checksum
f90a4cb1da73: Download complete
f90a4cb1da73: Pull complete
Digest: sha256:83551df73d724a2ea489400d90f7652deb5fcf4d620add018c1923f27d522bac
Status: Downloaded newer image for portainer/portainer-ce:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
be9c157a21496343ef252b026f8897b1ecf30c8f1ead0bba13984889bd3aab6c
[  OK  ] DietPi-Software | docker run -d -p 9002:9000 --name=portainer --restart=always -v /run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce
[  OK  ] DietPi-Autostart | systemctl daemon-reload
```

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
