### PR TITLE
Homer: Wrong capitalization lead to copy error when trying to apply MacOS theme.

### PR DESCRIPTION
**Pull request by JappeHallunken**
See also: https://dietpi.com/forum/t/issue-with-homer-theme-documentation/15563
Wrong capitalization lead to the error `cp: cannot stat 'Homer-Theme-main/custom.css': No such file or directory` when trying to copy the tmp files to the homer directory.

### CODE REVIEW

**Comment by StephanStS** [comment]
@JappeHallunken: I changed the base branch from master to dev. We do doc changes in these steps:
1. Editing doc and doing a PR into the dev branch
2. Cyclically (typically every week) we do a PR from dev to master

Remarks:
- Some PRs remain in their branches and are merged to dev short before a release date. This is done in cases of docu changes which need to be in sync with the release date
- To add me as reviewer is good, this triggers me to look at the PR. I then also look for other attributes like Labels etc. and set them accordingly, resp. add further reviewers
- Actually the required checks (-> actions) often fail, I then sometimes try to get rid of this by re-running the checks manually

Thx.

**Comment by MichaIng** [comment]
Thanks. Makes sense, the archive names match precisely the repo names + branch name.

> This theme also provides another wallpaper: wallpaper-light.jpeg

Does it make sense to mention this in the config below as option, or adjust the steps to copy either `wallpaper.jpeg` or `wallpaper-light.jpeg`? Otherwise I guess most users will have `wallpaper-light.jpeg` remaining unused.

**Review by StephanStS — APPROVED** [review]

**Comment by StephanStS** [comment]
@JappeHallunken: Link check is running now, so a "squash & merge" is possible as the next step.
Open is only Micha's question above.

**Comment by JappeHallunken** [comment]
There is a button on the web GUI to switch on the fly between light and dark mode.
But I encountered another issue. We could skip the whole step for editing manually the `config,yml` if we copy the whole assets folder instead of only the fonts, it contains everything needed (config.yml, fonts etc). (the cp command for this is BTW currently also wrong, but I wanted to ask you about your opinion how to handle this before making more changes; the cp should be `cp -R homer-theme-main/assets/fonts ...` the `assets` path is missing currently in our command in the docs.
But there is also another issue, this config.yml contains:
`background-image: "../assets/wallpaper-light.jpeg"` (same for light theme)
which leads to a 404 for the background images, since the path on the dietpi installation is `"../homer/assets/wallpaper-light.jpeg"`. So a manually modification would be needed also in every case, What do you think would be best practice to handle this?
Maybe copy the whole assets folder but change the instructions to change this two lines, for the background images?

**Comment by MichaIng** [comment]
Great catches. I do now understand better how the theming and dark/light mode works: General theming goes into CSS and dark/light mode specific parts go into `config.yml`.

The problem with copying `config.yml` from the theme is that it overwrites all previously configured services (replacing them with two boring ones 😛) and other non-theming related settings. The only parts really related to the theme are the `stylesheet:` and the `colors:` blocks. Nice would be a simple command to merge only those two blocks. I guess there are YAML parser/writer tools, but maybe we find some nice `sed`/`awk` for this.

Two further bugs in your current `config.yml` example, if we want to keep it:
- `light:` and `dark:` need to be indented by two additional spaces. Those are intended to be part of the `colors:` block, otherwise I guess light/dark switch won't fully work.
- In `light:`, the `background-image:` now can/should be `../assets/wallpaper-light.jpeg` to make use of the light background that is now copied.

**Comment by JappeHallunken** [comment]
Ah yes, this makes perfectly sense now to me, why it's handled like this in the docs.
For now I will fix the two issues you mentioned.

**Comment by JappeHallunken** [comment]
There would be even more customizations necessary, e.g. in this theme is no header activated, it would be necessary to deactivate it via the config,yml. Leaving it activated for this theme leads to white text on white background in the header. Also here and there some colors are missing / not set correctly, for stuff like the optional message, links below the header etc.

Maybe it would be indeed best practice to remove everything except the `services:` section and copying the rest from the new theme-config. But this theme makes also some customizations there, e.g. introducing `tagstyle: "is-primary"`.

But on the other hand I assume somebody who changes the theme for homer is also capable figuring this stuff out for himself, so no need to adress this further, or what do you think?

**Comment by MichaIng** [comment]
> Maybe it would be indeed best practice to remove everything except the `services:` section and copying the rest from the new theme-config.

Your personal Homer's title, logo, number of service/link columns and such are not part of the theme I'd say. Good point with the header, probably we can contribute a little CSS change to make headers look nice with this theme 😃. Until then we could add it as disabled with a comment in the example YAML.

> But this theme makes also some customizations there, e.g. introducing `tagstyle: "is-primary"`.

It only adds its own GitHub repository and Reddit post to the dashboard as a starting point and self-advertisement, highlighting the GitHub repo with "primary" style, same with the footer. I cannot imagine anymore who wants/leaves these in place. The only argument for those is that it's fair for the themes developer, but I think such credits are better placed in our docs.

One argument for copying the YAML or copying the style blocks from it, is that we do not need to keep ours updated. It is not heavily developed, but things do change, like the repo owner/name capitalisation (it indeed was with capital letters when these docs were implemented).

@t3dium 
As you implemented Homer and the theming docs, any opinion on this?

If in doubt, I'd go with the fixes for now.

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
Let's merge these fixes. Further changes can be done in a follow-up PR.

**Pull request merged**
