### PR TITLE
Created homepages page + homer documentation

### PR DESCRIPTION
**Pull request by t3dium**

### CODE REVIEW

**Comment by MichaIng** [comment]
@t3dium 
Do you find time to update the docs according to the changes we did? We'll btw move it to "System Stats & Management" category, where it currently fits slightly better.

**Comment by t3dium** [comment]
Oh yeah i forgot to update that, I'll make the changes

**Comment by StephanStS** [comment]
@MichaIng: Please merge it for now into the dev branch (with all failed checks), afterwards I do some more minor modifications (which I cannot do on the fork of t3dium). Also doing it as a review is less ease of use for me.

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
Okay, I'm fine with content, format can be fixed in dev.

**Pull request merged**
